- title: Pangyo AI Camp
  desc: 1st Prize, A classification model of risk behavior for children's road walking to protect children and the transportation vulnerable.
  icon: assets/images/services-icon-gbsa.png

- title: Pangyo AI Camp
  desc: 3rd Prize, Classification of whether to wear a mask to prevent COVID-19.
  icon: assets/images/services-icon-gbsa.png

- title: EXCEL Creative Comprehensive Design Competition
  desc: Manufacturing smart air conditioners using Peltier devices.
  icon: assets/images/services-icon-hanyang.png